version: "3.9"

services:
  database:
    image: mysql
    ports:
      - "3310:3306"
    environment:
      # Root username is root
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: wiki-watch
