[tool.poetry]
name = "wiki-watch"
version = "0.1.0"
description = ""
authors = ["Charlie Cumber <chukc@hotmail.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
